name: Deploy to GitHub Pages and Run Backend

# This workflow will run every time you push to the 'main' branch
on:
  push:
    branches:
      - main # Trigger when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Check out your source code repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify Node.js version (adjust if necessary)

      - name: Install pm2 package
        run: npm install -g pm2

      - name: Install dependencies
        run: npm install # Install your project dependencies (like Webpack)

      - name: Build project
        run: |
          echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" > .env
          npm run build # This will run the Webpack build process

  backend:
    runs-on: ubuntu-latest
    needs: build # Ensure backend job runs after build job completes

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16" # Adjust if necessary

      - name: Install backend dependencies
        run: npm install # Install dependencies specific to your backend

      - name: Install pm2 package
        run: npm install -g pm2

      - name: Start backend server
        run: pm2 start backend/server.js --name "my-backend-server"

  deploy:
    runs-on: ubuntu-latest
    needs: backend # Ensure deploy job runs after backend job completes

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
